import SmoothScrollWrapper from "@/components/Hooks/SmoothScrollWrapper";
import "./globals.css";
import DynamicNavbar from "@/components/Homepage/DynamicNav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SmoothScrollWrapper> */}
          <DynamicNavbar/>
        {children}
        {/* </SmoothScrollWrapper> */}
        </body>
    </html>
  );
}
